apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: beautifulthings-app-tls
  namespace: default
spec:
  secretName: beautifulthings-app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: beautifulthings.app
  dnsNames:
  - beautifulthings.app
  acme:
    config:
    - http01:
        ingress: beautifulthings-ingress
      domains:
      - beautifulthings.app
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: 'chiiph@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-staging
    http01: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'chiiph@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}

